### ISSUE TITLE
Documentation is lacking in API usage.

### ISSUE THREAD

**Issue by JTeijema** [asreview/asreview-datatools#10]
```python
from asreviewcontrib.statistics import StateStatistics

from contextlib import redirect_stdout

with open('out.txt', 'w') as f:
    with redirect_stdout(f):
        for file in files:
            print(StateStatistics.from_path(file, wss_vals=[95, 100]))
```

In this example, I collect statistics for many runs simultaneously and store them in a file.

The API can be handy and is very easy to use, but the documentation regarding this usage is non-existent. There is also no separate page in the ASReview documentation. I'd suggest modifying the readme.MD for now, and adding a separate page later.

**Comment by J535D165** [comment]
Thanks for reporting. Makes sense to document parts of it. We are moving parts of this library to ASReview itself. Over there, the API is documented. This might solve the issue. 

Dataset stats -> https://github.com/asreview/asreview/blob/master/asreview/data/statistics.py
Active learning metrics -> https://github.com/asreview/asreview/pull/787

Given this ongoing work, it's is not advised to contribute to this issue (by adding this documentation). Contributions to the items above are very welcome.

**Comment by J535D165** [comment]
This issue is still relevant, but the context is different now. It fits the context of https://github.com/asreview/asreview-insights better. However, API documentation for datatools is also nice to have. The API is straightforward, but documentation will help many users.

I feel like closing this issue and opening a new one with the relevant context.
